//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPSTONE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAPSTONEEntities1 : DbContext
    {
        public CAPSTONEEntities1()
            : base("name=CAPSTONEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tb> Admin_tb { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<UsersTbl> UsersTbls { get; set; }
        public virtual DbSet<Product1> Products1 { get; set; }
    }
}
